displayName: Opa Plugin
type: middleware
iconPath: .assets/icon.png

import: github.com/joaopaulovw/opa-traefik-plugin

summary: 'Opa middleware'

testData:
  Endpoint: http://localhost/v1/data/example
  Allow: allow
